# Generated by Django 6.0.4 on 2026-06-30 08:11

from django.db import migrations

SPECIALITIES = [
    'plumber', 'electrician', 'carpenter', 'tailor',
    'barber', 'hairstylist', 'makeup_artist'
]


def seed_specialities(apps, schema_editor):
    Speciality = apps.get_model('users', 'Speciality')
    for name in SPECIALITIES:
        Speciality.objects.get_or_create(name=name)


def reverse_seed(apps, schema_editor):
    Speciality = apps.get_model('users', 'Speciality')
    Speciality.objects.filter(name__in=SPECIALITIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_speciality_remove_artisanprofile_speciality_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_specialities, reverse_seed),
    ]
